<a href="https://colab.research.google.com/github/th900/An-lise-de-Vendas-e-Lucratividade-no-Varejo/blob/main/Retail_Sales_%26_Profitability_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'superstore-dataset-final' dataset.
Path to dataset files: /kaggle/input/superstore-dataset-final

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/kaggle/input/superstore-dataset-final/Sample - Superstore.csv', encoding='latin1')

In [3]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [6]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
df = df.drop_duplicates()

In [8]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [10]:
print("Período dos pedidos:")
print(df["Order Date"].min(), "até", df["Order Date"].max())

print("\nPeríodo dos envios:")
print(df["Ship Date"].min(), "até", df["Ship Date"].max())

print("\nDatas de envio anteriores ao pedido:")
print((df["Ship Date"] < df["Order Date"]).sum())

Período dos pedidos:
2014-01-03 00:00:00 até 2017-12-30 00:00:00

Período dos envios:
2014-01-07 00:00:00 até 2018-01-05 00:00:00

Datas de envio anteriores ao pedido:
0

In [11]:
df["Shipping days"] = (df["Ship Date"] - df["Order Date"]).dt.days
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.month_name()

In [12]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping days,Order Year,Order Month,Order Month Name
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,November
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,November
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,June
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,October
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,October
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2,2014,1,January
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,5,2017,2,February
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,5,2017,2,February
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,5,2017,2,February
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5,2017,5,May

In [13]:
(df["Sales"]==0).sum()

np.int64(0)

In [14]:
print("Linhas:", len(df))
print("Pedidos únicos:", df["Order ID"].nunique())
print("Clientes únicos:", df["Customer ID"].nunique())
print("Produtos únicos:", df["Product ID"].nunique())

Linhas: 9994
Pedidos únicos: 5009
Clientes únicos: 793
Produtos únicos: 1862

In [15]:
df["profit margin"] = df["Profit"]/df["Sales"]

In [16]:
df["Discount"].describe()

count    9994.000000
mean        0.156203
std         0.206452
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [17]:
df["Discount"].value_counts().sort_index()

Discount
0.00    4798
0.10      94
0.15      52
0.20    3657
0.30     227
0.32      27
0.40     206
0.45      11
0.50      66
0.60     138
0.70     418
0.80     300
Name: count, dtype: int64

In [18]:
df.loc[df["Discount"] > 0.70, "profit margin"]

14     -1.80
15     -1.50
75     -1.55
101    -1.70
169    -2.55
        ...
9794   -1.70
9795   -1.55
9808   -1.60
9835   -1.60
9920   -1.60
Name: profit margin, Length: 300, dtype: float64

In [19]:
discount_analysis = (
    df.groupby("Discount")
      .agg(
          Sales=("Sales", "sum"),
          Profit=("Profit", "sum"),
          Orders=("Order ID", "nunique")
      )
)

discount_analysis["profit margin"] = (
    discount_analysis["Profit"] /
    discount_analysis["Sales"]
)

discount_analysis

                 Sales       Profit  Orders  profit margin
Discount
0.00      1.087908e+06  320987.6032    2644       0.295050
0.10      5.436935e+04    9029.1770      89       0.166071
0.15      2.755852e+04    1418.9915      51       0.051490
0.20      7.645944e+05   90337.3060    2407       0.118151
0.30      1.032267e+05  -10369.2774     211      -0.100452
0.32      1.449346e+04   -2391.1377      27      -0.164980
0.40      1.164178e+05  -23057.0504     185      -0.198054
0.45      5.484974e+03   -2493.1111      10      -0.454535
0.50      5.891854e+04  -20506.4281      64      -0.348047
0.60      6.644700e+03   -5944.6552     127      -0.894646
0.70      4.062028e+04  -40075.3569     344      -0.986585
0.80      1.696376e+04  -30539.0392     250      -1.800252

In [20]:
df[df["Discount"] > 0.70].agg({
    "Sales": "sum",
    "Quantity": "sum",
    "Profit": "sum"
})

Sales       16963.7560
Quantity     1188.0000
Profit     -30539.0392
dtype: float64

In [21]:
high_discount = (
    df[df["Discount"] >= 0.30]
    .groupby(["Category", "Sub-Category"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum"),
        Orders=("Order ID", "nunique")
    )
)

high_discount["profit margin"] = (
    high_discount["Profit"] /
    high_discount["Sales"]
)

high_discount.sort_values("profit margin")

                                   Sales      Profit  Quantity  Orders  \
Category        Sub-Category
Office Supplies Appliances     3382.5340  -8629.6412       235      65
                Binders       36140.6130 -38510.4964      2456     526
Furniture       Furnishings    6644.7000  -5944.6552       501     127
                Bookcases     28543.9988 -11097.7614       292      69
Technology      Machines      76839.1080 -29555.3521       180      50
Furniture       Tables        89956.5400 -30698.2228       650     168
Technology      Phones        34337.3520  -6385.7854       414      98
Furniture       Chairs        70005.5020  -6737.1167       614     149
Technology      Copiers       16919.8020   2182.9752        33       9

                              profit margin
Category        Sub-Category
Office Supplies Appliances        -2.551236
                Binders           -1.065574
Furniture       Furnishings       -0.894646
                Bookcases         -0.388795
Technology      Machines          -0.384639
Furniture       Tables            -0.341256
Technology      Phones            -0.185972
Furniture       Chairs            -0.096237
Technology      Copiers            0.129019

In [22]:
subcategory_discount = (
    df.groupby(["Sub-Category", "Discount"])
      .agg(
          Sales=("Sales", "sum"),
          Profit=("Profit", "sum"),
          Orders=("Order ID", "nunique")
      )
)

subcategory_discount["Profit Margin"] = (
    subcategory_discount["Profit"] /
    subcategory_discount["Sales"]
)

subcategory_discount

                             Sales      Profit  Orders  Profit Margin
Sub-Category Discount
Accessories  0.00      118370.3100  35289.2539     435       0.298126
             0.20       49010.0080   6647.3818     283       0.135633
Appliances   0.00       78066.1900  23183.7361     265       0.296975
             0.10        4324.1490   1086.0808      16       0.251166
             0.20       21759.2880   2497.8297     105       0.114794
             0.80        3382.5340  -8629.6412      65      -2.551236
Art          0.00       18014.6400   5380.6006     452       0.298679
             0.20        9104.1520   1147.1864     279       0.126007
Binders      0.00       81829.4800  39314.4507     295       0.480444
             0.20       85442.6400  29417.8090     495       0.344299
             0.70       22559.3910 -16601.0984     323      -0.735884
             0.80       13581.2220 -21909.3980     203      -1.613213
Bookcases    0.00       31935.9800   6075.7117      60       0.190247
             0.15       27558.5215   1418.9915      51       0.051490
             0.20       26841.4960    130.5022      44       0.004862
             0.30        4282.6980   -555.8726       9      -0.129795
             0.32       14493.4588  -2391.1377      27      -0.164980
             0.50        7308.4600  -4255.8117      18      -0.582313
             0.70        2459.3820  -3894.9394      15      -1.583707
Chairs       0.00       91060.7300  21933.0961     124       0.240862
             0.10       46634.2470   7111.0119      71       0.152485
             0.20      120748.6240   4283.1750     232       0.035472
             0.30       70005.5020  -6737.1167     149      -0.096237
Copiers      0.00       76449.1800  35556.1349      22       0.465095
             0.20       56159.0480  17878.7148      37       0.318359
             0.40       16919.8020   2182.9752       9       0.129019
Envelopes    0.00       10606.4500   4976.9844     148       0.469241
             0.20        5869.9520   1987.1923     101       0.338536
Fasteners    0.00        1822.8400    652.2052     128       0.357796
             0.20        1201.4400    297.3130      87       0.247464
Furnishings  0.00       61449.8000  16847.9689     529       0.274175
             0.20       23610.6640   2155.8299     221       0.091307
             0.60        6644.7000  -5944.6552     127      -0.894646
Labels       0.00        9239.5600   4422.0960     225       0.478605
             0.20        3246.7520   1124.1580     121       0.346241
Machines     0.00       71034.0000  27137.8223      29       0.382040
             0.10        3410.9550    832.0843       2       0.243945
             0.20       37954.5680   4970.2024      31       0.130951
             0.30        3756.3050    326.0395       5       0.086798
             0.40       19546.2240  -2666.8434      12      -0.136438
             0.50       37935.0700  -7635.2291      11      -0.201271
             0.70       15601.5090 -19579.3191      22      -1.254963
Paper        0.00       53157.8700  25329.4677     737       0.476495
             0.20       25321.3360   8724.1016     454       0.344536
Phones       0.00      123879.7100  34365.2093     278       0.277408
             0.20      171789.9920  16536.3067     438       0.096259
             0.40       34337.3520  -6385.7854      98      -0.185972
Storage      0.00      157853.7600  25528.1715     484       0.161720
             0.20       65989.8480  -4249.3451     293      -0.064394
Supplies     0.00       31559.2100   1718.3942     115       0.054450
             0.20       15114.3280  -2907.4937      72      -0.192367
Tables       0.00       71578.7600  13276.2997      70       0.185478
             0.20       45430.2320   -303.5580      69      -0.006682
             0.30       25182.1500  -3402.3276      51      -0.135109
             0.40       45614.4060 -16187.3968      72      -0.354875
             0.45        5484.9740  -2493.1111      10      -0.454535
             0.50       13675.0100  -8615.3873      35      -0.630010

1.Descontos elevados estão fortemente associados à deterioração da margem.

2.O impacto do desconto varia muito por subcategoria.

3.Algumas subcategorias começam a apresentar prejuízo já com 20% de desconto.

4.Binders, Tables e Machines apresentam perdas financeiras relevantes em níveis
elevados de desconto.

5.Copiers é uma exceção: permanece lucrativo mesmo com 40% de desconto.

6.A Central possui a menor margem regional.

7.A Central apresenta uma concentração particularmente problemática de vendas com 80% de desconto.

In [23]:
regional_analysis = (
    df.groupby("Region")
      .agg(
          Sales=("Sales", "sum"),
          Profit=("Profit", "sum"),
          Quantity=("Quantity", "sum"),
          Orders=("Order ID", "nunique"),
          Customers=("Customer ID", "nunique")
      )
)

regional_analysis["Profit Margin"] = (
    regional_analysis["Profit"] /
    regional_analysis["Sales"]
)
regional_analysis.sort_values("Profit", ascending=False)

               Sales       Profit  Quantity  Orders  Customers  Profit Margin
Region
West     725457.8245  108418.4489     12266    1611        686       0.149448
East     678781.2400   91522.7800     10618    1401        674       0.134834
South    391721.9050   46749.4303      6209     822        512       0.119343
Central  501239.8908   39706.3625      8780    1175        629       0.079216

In [24]:
region_discount = (
    df.groupby(["Region", "Discount"])
      .agg(
          Sales=("Sales", "sum"),
          Profit=("Profit", "sum"),
          Orders=("Order ID", "nunique")
      )
)

region_discount["Profit Margin"] = (
    region_discount["Profit"] /
    region_discount["Sales"]
)

region_discount

                        Sales       Profit  Orders  Profit Margin
Region  Discount
Central 0.00      243150.6400   76125.4407     410       0.313079
        0.10        7735.1040    1918.1651      18       0.247982
        0.20      121220.0480   14055.0311     550       0.115946
        0.30       64935.2900   -6540.8542     137      -0.100729
        0.32       14493.4588   -2391.1377      27      -0.164980
        0.40       19546.2240   -2666.8434      12      -0.136438
        0.50        6550.6700   -4309.7447      17      -0.657909
        0.60        6644.7000   -5944.6552     127      -0.894646
        0.80       16963.7560  -30539.0392     250      -1.800252
East    0.00      341742.5400  105377.5464     768       0.308354
        0.10       46634.2470    7111.0119      71       0.152485
        0.20      144534.0560   21122.8293     590       0.146144
        0.30       38291.3650   -3828.4232      74      -0.099981
        0.40       80975.4720  -14042.5393     157      -0.173417
        0.50        7308.4600   -4255.8117      18      -0.582313
        0.70       19295.1000  -19961.8334     153      -1.034555
South   0.00      215983.1600   62981.3378     395       0.291603
        0.20      105021.7520    8648.5743     379       0.082350
        0.40       15896.0880   -6347.6677      16      -0.399323
        0.45        5484.9740   -2493.1111      10      -0.454535
        0.50       37935.0700   -7635.2291      11      -0.201271
        0.70       11400.8610   -8404.4739     112      -0.737179
West    0.00      287032.1300   76503.2783    1071       0.266532
        0.15       27558.5215    1418.9915      51       0.051490
        0.20      393818.5120   46510.8713     888       0.118102
        0.50        7124.3400   -4305.6426      18      -0.604357
        0.70        9924.3210  -11709.0496      79      -1.179834

In [25]:
region_category = (
    df.groupby(["Region", "Category"])
      .agg(
          Sales=("Sales", "sum"),
          Profit=("Profit", "sum"),
          Orders=("Order ID", "nunique")
      )
)

region_category["Profit Margin"] = (
    region_category["Profit"] /
    region_category["Sales"]
)

region_category

                               Sales      Profit  Orders  Profit Margin
Region  Category
Central Furniture        163797.1638  -2871.0494     403      -0.017528
        Office Supplies  167026.4150   8879.9799     880       0.053165
        Technology       170416.3120  33697.4320     356       0.197736
East    Furniture        208291.2040   3046.1658     488       0.014625
        Office Supplies  205516.0550  41014.5791    1074       0.199569
        Technology       264973.9810  47462.0351     443       0.179120
South   Furniture        117298.6840   6771.2061     278       0.057726
        Office Supplies  125651.3130  19986.3928     619       0.159062
        Technology       148771.9080  19991.8314     255       0.134379
West    Furniture        252612.7435  11504.9503     595       0.045544
        Office Supplies  220853.2490  52609.8490    1169       0.238212
        Technology       251991.8320  44303.6496     490       0.175814

Central : Furniture tem margem negativa e Office Supplies está bem abaixo quando comparamos com as outras regiões. Isso pode estar relacionado com desconto?

In [26]:
central_furniture = (
    df[
        (df["Region"] == "Central") &
        (df["Category"] == "Furniture")
    ]
    .groupby("Discount")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
)

central_furniture["Profit Margin"] = (
    central_furniture["Profit"] /
    central_furniture["Sales"]
)

central_furniture

               Sales      Profit  Orders  Profit Margin
Discount
0.00      74929.3500  16641.3819     130       0.222094
0.30      61178.9850  -6866.8937     133      -0.112243
0.32      14493.4588  -2391.1377      27      -0.164980
0.50       6550.6700  -4309.7447      17      -0.657909
0.60       6644.7000  -5944.6552     127      -0.894646

In [27]:
central_office = (
    df[
        (df["Region"] == "Central") &
        (df["Category"] == "Office Supplies")
    ]
    .groupby("Discount")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
)

central_office["Profit Margin"] = (
    central_office["Profit"] /
    central_office["Sales"]
)

central_office

              Sales      Profit  Orders  Profit Margin
Discount
0.0       98303.830  34732.6993     307       0.353320
0.1        4324.149   1086.0808      16       0.251166
0.2       47434.680   3600.2390     430       0.075899
0.8       16963.756 -30539.0392     250      -1.800252

In [28]:
central_furniture_sub = (
    df[
        (df["Region"] == "Central") &
        (df["Category"] == "Furniture")
    ]
    .groupby(["Sub-Category", "Discount"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
)

central_furniture_sub["Profit Margin"] = (
    central_furniture_sub["Profit"] /
    central_furniture_sub["Sales"]
)

central_furniture_sub.sort_values("Profit")

                            Sales      Profit  Orders  Profit Margin
Sub-Category Discount
Furnishings  0.60       6644.7000  -5944.6552     127      -0.894646
Tables       0.50       6550.6700  -4309.7447      17      -0.657909
Chairs       0.30      41135.6260  -4094.3445      95      -0.099533
Bookcases    0.32      14493.4588  -2391.1377      27      -0.164980
Tables       0.30      15760.6610  -2216.6766      31      -0.140646
Bookcases    0.30       4282.6980   -555.8726       9      -0.129795
             0.00       5381.0200    949.1060      13       0.176380
Furnishings  0.00       8609.6700   2038.4384      64       0.236762
Tables       0.00      16843.6400   2966.7709      20       0.176136
Chairs       0.00      44095.0200  10687.0666      49       0.242364

In [29]:
central_office_80 = (
    df[
        (df["Region"] == "Central") &
        (df["Category"] == "Office Supplies") &
        (df["Discount"] == 0.80)
    ]
    .groupby("Sub-Category")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
)

central_office_80["Profit Margin"] = (
    central_office_80["Profit"] /
    central_office_80["Sales"]
)

central_office_80.sort_values("Profit")

                  Sales      Profit  Orders  Profit Margin
Sub-Category
Binders       13581.222 -21909.3980     203      -1.613213
Appliances     3382.534  -8629.6412      65      -2.551236

1. Desconto × rentabilidade

Quanto maior o desconto, menor tende a ser a margem, com vários níveis tornando-se deficitários.

2. Limite de desconto varia por subcategoria

Não existe um único desconto "seguro" para todos os produtos.

3. Furniture no Central

A categoria é lucrativa sem desconto, mas passa a gerar prejuízo em níveis elevados de desconto.

4. Chairs

Um dos impactos mais relevantes dentro de Furniture: 95 pedidos a 30% de desconto geraram prejuízo.

5. Central + Office Supplies + 80%

250 pedidos geraram -$30.539 de prejuízo.

6. Binders

É o principal responsável pelo prejuízo desse grupo, com -$21.909.
7. Appliances

Tem a pior margem nesse grupo (-255,1%), mas seu impacto absoluto é menor que o de Binders.

8. Região

Central possui a menor margem regional (7,92%), enquanto West possui a maior (14,94%).

9. Categoria × região

O problema do Central não está distribuído igualmente entre categorias; Furniture é negativa e Office Supplies apresenta margem bem inferior às demais regiões.

10. Volume ≠ rentabilidade

Uma região ou categoria pode ter vendas maiores e ainda assim gerar menos lucro.

In [30]:
df_final = df.copy()

In [31]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   object
 2   Order Date        9994 non-null   datetime64[ns]
 3   Ship Date         9994 non-null   datetime64[ns]
 4   Ship Mode         9994 non-null   object
 5   Customer ID       9994 non-null   object
 6   Customer Name     9994 non-null   object
 7   Segment           9994 non-null   object
 8   Country           9994 non-null   object
 9   City              9994 non-null   object
 10  State             9994 non-null   object
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   object
 13  Product ID        9994 non-null   object
 14  Category          9994 non-null   object
 15  Sub-Category      9994 non-null   object
 16  Product Name      9994 non-null   object
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  Shipping days     9994 non-null   int64
 22  Order Year        9994 non-null   int32
 23  Order Month       9994 non-null   int32
 24  Order Month Name  9994 non-null   object
 25  profit margin     9994 non-null   float64
dtypes: datetime64[ns](2), float64(4), int32(2), int64(4), object(14)
memory usage: 1.9+ MB

In [33]:
df_final.columns = [
    "row_id",
    "order_id",
    "order_date",
    "ship_date",
    "ship_mode",
    "customer_id",
    "customer_name",
    "segment",
    "country",
    "city",
    "state",
    "postal_code",
    "region",
    "product_id",
    "category",
    "sub_category",
    "product_name",
    "sales",
    "quantity",
    "discount",
    "profit",
    "shipping days",
    "order_year",
    "order_month",
    "order_month_name",
    "profit margin"
]

In [38]:
df_final = df_final.drop(columns=["profit margin"])

In [39]:
print("Linhas:", len(df_final))
print("Colunas:", len(df_final.columns))

print("Nulos:")
print(df_final.isnull().sum())

print("Duplicados:", df_final.duplicated().sum())

Linhas: 9994
Colunas: 25
Nulos:
row_id              0
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
customer_name       0
segment             0
country             0
city                0
state               0
postal_code         0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
discount            0
profit              0
shipping days       0
order_year          0
order_month         0
order_month_name    0
dtype: int64
Duplicados: 0

In [40]:
df_final.to_csv(
    "retail_sales_clean.csv",
    index=False,
    encoding="utf-8-sig"
)